package com.chen.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-06T13:28:23.239+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://webservice.chen.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://webservice.chen.com/", className = "com.chen.webservice.HelloWorld_Type")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://webservice.chen.com/", className = "com.chen.webservice.HelloWorldResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
